font_family JetBrainsMono Nerd Font Mono
font_size   14

disable_ligatures no 
enable_audio_bell no

shell             zsh 
shell_integration disabled 

cursor_shape      block

url_style         curly

remember_window_size  no
initial_window_width   640 
initial_window_height  480 
window_padding_width  5
cursor_blink_interval 0

background_opacity             0.80
scrollbar_handle_capacity      0
scrollbar_track_capacity       0
scrollbar_track_hover_capacity 0
confirm_os_window_close        0

sync_to_monitor no

# Colors below
background            #000f19
foreground            #00e5ff
cursor                #00e5ff
selection_background  #003344
selection_foreground  #00e5ff

# Black
color0                #0a1628
color8                #1a3a4a

# Red
color1                #ff2e2e
color9                #ff6060

# Green
color2                #00ff9f
color10               #00cc80

# Yellow
color3                #ffe600
color11               #ffd000

# Blue
color4                #005f87
color12               #00a8cc

# Magenta
color5                #0096aa
color13               #00c8e0

# Cyan
color6                #00e5ff
color14               #80f0ff

# White
color7                #a0d8e8
color15               #cceeff